### ISSUE TITLE
Please, Remove console.log from request.ts.

### ISSUE THREAD

**Issue by sasanj** [ukaoskid/telegram-bot-api#1]
`console.log` should be removed  from [`telegram-bot-api/src/models/request.ts`](https://github.com/ukaoskid/telegram-bot-api/blob/269538c23345cd2261bcf6ebdae956c463e94056/src/models/request.ts#L16). 
it is better to use something like [Debug](https://www.npmjs.com/package/debug).

**Comment by sasanj** [comment]
Added a pull request to address this issue: [removed logging to console from request](https://github.com/ukaoskid/telegram-bot-api/pull/2)

**Comment by ukaoskid** [comment]
Solved by @sasanj 
Thanks for your effort!
